export interface Country {
    code: string;
    dial_code: string;
    flag: string;
    name: string;
}

export const COMMON_COUNTRIES: Country[] = [
    { code: 'US', dial_code: '+1', flag: '🇺🇸', name: 'United States' },
    { code: 'DZ', dial_code: '+213', flag: '🇩🇿', name: 'Algeria' },
    { code: 'AO', dial_code: '+244', flag: '🇦🇴', name: 'Angola' },
    { code: 'AU', dial_code: '+61', flag: '🇦🇺', name: 'Australia' },
    { code: 'BJ', dial_code: '+229', flag: '🇧🇯', name: 'Benin' },
    { code: 'BW', dial_code: '+267', flag: '🇧🇼', name: 'Botswana' },
    { code: 'BR', dial_code: '+55', flag: '🇧🇷', name: 'Brazil' },
    { code: 'BF', dial_code: '+226', flag: '🇧🇫', name: 'Burkina Faso' },
    { code: 'BI', dial_code: '+257', flag: '🇧🇮', name: 'Burundi' },
    { code: 'CM', dial_code: '+237', flag: '🇨🇲', name: 'Cameroon' },
    { code: 'CA', dial_code: '+1', flag: '🇨🇦', name: 'Canada' },
    { code: 'CV', dial_code: '+238', flag: '🇨🇻', name: 'Cape Verde' },
    { code: 'CF', dial_code: '+236', flag: '🇨🇫', name: 'Central African Republic' },
    { code: 'TD', dial_code: '+235', flag: '🇹🇩', name: 'Chad' },
    { code: 'CG', dial_code: '+242', flag: '🇨🇬', name: 'Congo - Brazzaville' },
    { code: 'CD', dial_code: '+243', flag: '🇨🇩', name: 'Congo - Kinshasa' },
    { code: 'DJ', dial_code: '+253', flag: '🇩🇯', name: 'Djibouti' },
    { code: 'EG', dial_code: '+20', flag: '🇪🇬', name: 'Egypt' },
    { code: 'GQ', dial_code: '+240', flag: '🇬🇶', name: 'Equatorial Guinea' },
    { code: 'ER', dial_code: '+291', flag: '🇪🇷', name: 'Eritrea' },
    { code: 'ET', dial_code: '+251', flag: '🇪🇹', name: 'Ethiopia' },
    { code: 'FR', dial_code: '+33', flag: '🇫🇷', name: 'France' },
    { code: 'GA', dial_code: '+241', flag: '🇬🇦', name: 'Gabon' },
    { code: 'GM', dial_code: '+220', flag: '🇬🇲', name: 'Gambia' },
    { code: 'DE', dial_code: '+49', flag: '🇩🇪', name: 'Germany' },
    { code: 'GH', dial_code: '+233', flag: '🇬🇭', name: 'Ghana' },
    { code: 'GN', dial_code: '+224', flag: '🇬🇳', name: 'Guinea' },
    { code: 'GW', dial_code: '+245', flag: '🇬🇼', name: 'Guinea-Bissau' },
    { code: 'IN', dial_code: '+91', flag: '🇮🇳', name: 'India' },
    { code: 'CI', dial_code: '+225', flag: '🇨🇮', name: 'Ivory Coast' },
    { code: 'JP', dial_code: '+81', flag: '🇯🇵', name: 'Japan' },
    { code: 'KE', dial_code: '+254', flag: '🇰🇪', name: 'Kenya' },
    { code: 'LS', dial_code: '+266', flag: '🇱🇸', name: 'Lesotho' },
    { code: 'LR', dial_code: '+231', flag: '🇱🇷', name: 'Liberia' },
    { code: 'LY', dial_code: '+218', flag: '🇱🇾', name: 'Libya' },
    { code: 'MG', dial_code: '+261', flag: '🇲🇬', name: 'Madagascar' },
    { code: 'MW', dial_code: '+265', flag: '🇲🇼', name: 'Malawi' },
    { code: 'ML', dial_code: '+223', flag: '🇲🇱', name: 'Mali' },
    { code: 'MR', dial_code: '+222', flag: '🇲🇷', name: 'Mauritania' },
    { code: 'MU', dial_code: '+230', flag: '🇲🇺', name: 'Mauritius' },
    { code: 'MA', dial_code: '+212', flag: '🇲🇦', name: 'Morocco' },
    { code: 'MZ', dial_code: '+258', flag: '🇲🇿', name: 'Mozambique' },
    { code: 'NA', dial_code: '+264', flag: '🇳🇦', name: 'Namibia' },
    { code: 'NE', dial_code: '+227', flag: '🇳🇪', name: 'Niger' },
    { code: 'NG', dial_code: '+234', flag: '🇳🇬', name: 'Nigeria' },
    { code: 'RW', dial_code: '+250', flag: '🇷🇼', name: 'Rwanda' },
    { code: 'ST', dial_code: '+239', flag: '🇸🇹', name: 'Sao Tome & Principe' },
    { code: 'SN', dial_code: '+221', flag: '🇸🇳', name: 'Senegal' },
    { code: 'SC', dial_code: '+248', flag: '🇸🇨', name: 'Seychelles' },
    { code: 'SL', dial_code: '+232', flag: '🇸🇱', name: 'Sierra Leone' },
    { code: 'SO', dial_code: '+252', flag: '🇸🇴', name: 'Somalia' },
    { code: 'ZA', dial_code: '+27', flag: '🇿🇦', name: 'South Africa' },
    { code: 'SS', dial_code: '+211', flag: '🇸🇸', name: 'South Sudan' },
    { code: 'SD', dial_code: '+249', flag: '🇸🇩', name: 'Sudan' },
    { code: 'SZ', dial_code: '+268', flag: '🇸🇿', name: 'Eswatini' },
    { code: 'TZ', dial_code: '+255', flag: '🇹🇿', name: 'Tanzania' },
    { code: 'TG', dial_code: '+228', flag: '🇹🇬', name: 'Togo' },
    { code: 'TN', dial_code: '+216', flag: '🇹🇳', name: 'Tunisia' },
    { code: 'UG', dial_code: '+256', flag: '🇺🇬', name: 'Uganda' },
    { code: 'GB', dial_code: '+44', flag: '🇬🇧', name: 'United Kingdom' },
    { code: 'ZM', dial_code: '+260', flag: '🇿🇲', name: 'Zambia' },
    { code: 'ZW', dial_code: '+263', flag: '🇿🇼', name: 'Zimbabwe' },
];
