export type CountryCode = {
    code: string;
    iso: string;
    country: string;
    flag: string;
};

export const COUNTRY_CODES: CountryCode[] = [
    // United States - Always first
    { code: '+1', iso: 'US', country: 'United States', flag: '🇺🇸' },

    // All other countries alphabetically
    { code: '+355', iso: 'AL', country: 'Albania', flag: '🇦🇱' },
    { code: '+213', iso: 'DZ', country: 'Algeria', flag: '🇩🇿' },
    { code: '+376', iso: 'AD', country: 'Andorra', flag: '🇦🇩' },
    { code: '+244', iso: 'AO', country: 'Angola', flag: '🇦🇴' },
    { code: '+54', iso: 'AR', country: 'Argentina', flag: '🇦🇷' },
    { code: '+61', iso: 'AU', country: 'Australia', flag: '🇦🇺' },
    { code: '+43', iso: 'AT', country: 'Austria', flag: '🇦🇹' },
    { code: '+1-242', iso: 'BS', country: 'Bahamas', flag: '🇧🇸' },
    { code: '+880', iso: 'BD', country: 'Bangladesh', flag: '🇧🇩' },
    { code: '+1-246', iso: 'BB', country: 'Barbados', flag: '🇧🇧' },
    { code: '+375', iso: 'BY', country: 'Belarus', flag: '🇧🇾' },
    { code: '+32', iso: 'BE', country: 'Belgium', flag: '🇧🇪' },
    { code: '+501', iso: 'BZ', country: 'Belize', flag: '🇧🇿' },
    { code: '+229', iso: 'BJ', country: 'Benin', flag: '🇧🇯' },
    { code: '+591', iso: 'BO', country: 'Bolivia', flag: '🇧🇴' },
    { code: '+387', iso: 'BA', country: 'Bosnia and Herzegovina', flag: '🇧🇦' },
    { code: '+267', iso: 'BW', country: 'Botswana', flag: '🇧🇼' },
    { code: '+55', iso: 'BR', country: 'Brazil', flag: '🇧🇷' },
    { code: '+359', iso: 'BG', country: 'Bulgaria', flag: '🇧🇬' },
    { code: '+226', iso: 'BF', country: 'Burkina Faso', flag: '🇧🇫' },
    { code: '+257', iso: 'BI', country: 'Burundi', flag: '🇧🇮' },
    { code: '+855', iso: 'KH', country: 'Cambodia', flag: '🇰🇭' },
    { code: '+237', iso: 'CM', country: 'Cameroon', flag: '🇨🇲' },
    { code: '+1', iso: 'CA', country: 'Canada', flag: '🇨🇦' },
    { code: '+238', iso: 'CV', country: 'Cape Verde', flag: '🇨🇻' },
    { code: '+236', iso: 'CF', country: 'Central African Republic', flag: '🇨🇫' },
    { code: '+235', iso: 'TD', country: 'Chad', flag: '🇹🇩' },
    { code: '+56', iso: 'CL', country: 'Chile', flag: '🇨🇱' },
    { code: '+86', iso: 'CN', country: 'China', flag: '🇨🇳' },
    { code: '+57', iso: 'CO', country: 'Colombia', flag: '🇨🇴' },
    { code: '+269', iso: 'KM', country: 'Comoros', flag: '🇰🇲' },
    { code: '+242', iso: 'CG', country: 'Congo', flag: '🇨🇬' },
    { code: '+682', iso: 'CK', country: 'Cook Islands', flag: '🇨🇰' },
    { code: '+506', iso: 'CR', country: 'Costa Rica', flag: '🇨🇷' },
    { code: '+385', iso: 'HR', country: 'Croatia', flag: '🇭🇷' },
    { code: '+53', iso: 'CU', country: 'Cuba', flag: '🇨🇺' },
    { code: '+357', iso: 'CY', country: 'Cyprus', flag: '🇨🇾' },
    { code: '+420', iso: 'CZ', country: 'Czech Republic', flag: '🇨🇿' },
    { code: '+243', iso: 'CD', country: 'Democratic Republic of Congo', flag: '🇨🇩' },
    { code: '+45', iso: 'DK', country: 'Denmark', flag: '🇩🇰' },
    { code: '+253', iso: 'DJ', country: 'Djibouti', flag: '🇩🇯' },
    { code: '+1-767', iso: 'DM', country: 'Dominica', flag: '🇩🇲' },
    { code: '+1-809', iso: 'DO', country: 'Dominican Republic', flag: '🇩🇴' },
    { code: '+593', iso: 'EC', country: 'Ecuador', flag: '🇪🇨' },
    { code: '+20', iso: 'EG', country: 'Egypt', flag: '🇪🇬' },
    { code: '+503', iso: 'SV', country: 'El Salvador', flag: '🇸🇻' },
    { code: '+240', iso: 'GQ', country: 'Equatorial Guinea', flag: '🇬🇶' },
    { code: '+291', iso: 'ER', country: 'Eritrea', flag: '🇪🇷' },
    { code: '+372', iso: 'EE', country: 'Estonia', flag: '🇪🇪' },
    { code: '+268', iso: 'SZ', country: 'Eswatini', flag: '🇸🇿' },
    { code: '+251', iso: 'ET', country: 'Ethiopia', flag: '🇪🇹' },
    { code: '+500', iso: 'FK', country: 'Falkland Islands', flag: '🇫🇰' },
    { code: '+679', iso: 'FJ', country: 'Fiji', flag: '🇫🇯' },
    { code: '+358', iso: 'FI', country: 'Finland', flag: '🇫🇮' },
    { code: '+33', iso: 'FR', country: 'France', flag: '🇫🇷' },
    { code: '+594', iso: 'GF', country: 'French Guiana', flag: '🇬🇫' },
    { code: '+689', iso: 'PF', country: 'French Polynesia', flag: '🇵🇫' },
    { code: '+241', iso: 'GA', country: 'Gabon', flag: '🇬🇦' },
    { code: '+220', iso: 'GM', country: 'Gambia', flag: '🇬🇲' },
    { code: '+49', iso: 'DE', country: 'Germany', flag: '🇩🇪' },
    { code: '+233', iso: 'GH', country: 'Ghana', flag: '🇬🇭' },
    { code: '+30', iso: 'GR', country: 'Greece', flag: '🇬🇷' },
    { code: '+502', iso: 'GT', country: 'Guatemala', flag: '🇬🇹' },
    { code: '+224', iso: 'GN', country: 'Guinea', flag: '🇬🇳' },
    { code: '+245', iso: 'GW', country: 'Guinea-Bissau', flag: '🇬🇼' },
    { code: '+592', iso: 'GY', country: 'Guyana', flag: '🇬🇾' },
    { code: '+509', iso: 'HT', country: 'Haiti', flag: '🇭🇹' },
    { code: '+504', iso: 'HN', country: 'Honduras', flag: '🇭🇳' },
    { code: '+852', iso: 'HK', country: 'Hong Kong', flag: '🇭🇰' },
    { code: '+36', iso: 'HU', country: 'Hungary', flag: '🇭🇺' },
    { code: '+354', iso: 'IS', country: 'Iceland', flag: '🇮🇸' },
    { code: '+91', iso: 'IN', country: 'India', flag: '🇮🇳' },
    { code: '+62', iso: 'ID', country: 'Indonesia', flag: '🇮🇩' },
    { code: '+353', iso: 'IE', country: 'Ireland', flag: '🇮🇪' },
    { code: '+39', iso: 'IT', country: 'Italy', flag: '🇮🇹' },
    { code: '+225', iso: 'CI', country: 'Ivory Coast', flag: '🇨🇮' },
    { code: '+1-876', iso: 'JM', country: 'Jamaica', flag: '🇯🇲' },
    { code: '+81', iso: 'JP', country: 'Japan', flag: '🇯🇵' },
    { code: '+254', iso: 'KE', country: 'Kenya', flag: '🇰🇪' },
    { code: '+686', iso: 'KI', country: 'Kiribati', flag: '🇰🇮' },
    { code: '+383', iso: 'XK', country: 'Kosovo', flag: '🇽🇰' },
    { code: '+856', iso: 'LA', country: 'Laos', flag: '🇱🇦' },
    { code: '+371', iso: 'LV', country: 'Latvia', flag: '🇱🇻' },
    { code: '+266', iso: 'LS', country: 'Lesotho', flag: '🇱🇸' },
    { code: '+231', iso: 'LR', country: 'Liberia', flag: '🇱🇷' },
    { code: '+218', iso: 'LY', country: 'Libya', flag: '🇱🇾' },
    { code: '+370', iso: 'LT', country: 'Lithuania', flag: '🇱🇹' },
    { code: '+352', iso: 'LU', country: 'Luxembourg', flag: '🇱🇺' },
    { code: '+853', iso: 'MO', country: 'Macau', flag: '🇲🇴' },
    { code: '+261', iso: 'MG', country: 'Madagascar', flag: '🇲🇬' },
    { code: '+265', iso: 'MW', country: 'Malawi', flag: '🇲🇼' },
    { code: '+60', iso: 'MY', country: 'Malaysia', flag: '🇲🇾' },
    { code: '+223', iso: 'ML', country: 'Mali', flag: '🇲🇱' },
    { code: '+356', iso: 'MT', country: 'Malta', flag: '🇲🇹' },
    { code: '+692', iso: 'MH', country: 'Marshall Islands', flag: '🇲🇭' },
    { code: '+222', iso: 'MR', country: 'Mauritania', flag: '🇲🇷' },
    { code: '+230', iso: 'MU', country: 'Mauritius', flag: '🇲🇺' },
    { code: '+52', iso: 'MX', country: 'Mexico', flag: '🇲🇽' },
    { code: '+691', iso: 'FM', country: 'Micronesia', flag: '🇫🇲' },
    { code: '+373', iso: 'MD', country: 'Moldova', flag: '🇲🇩' },
    { code: '+377', iso: 'MC', country: 'Monaco', flag: '🇲🇨' },
    { code: '+382', iso: 'ME', country: 'Montenegro', flag: '🇲🇪' },
    { code: '+212', iso: 'MA', country: 'Morocco', flag: '🇲🇦' },
    { code: '+258', iso: 'MZ', country: 'Mozambique', flag: '🇲🇿' },
    { code: '+95', iso: 'MM', country: 'Myanmar', flag: '🇲🇲' },
    { code: '+264', iso: 'NA', country: 'Namibia', flag: '🇳🇦' },
    { code: '+977', iso: 'NP', country: 'Nepal', flag: '🇳🇵' },
    { code: '+31', iso: 'NL', country: 'Netherlands', flag: '🇳🇱' },
    { code: '+687', iso: 'NC', country: 'New Caledonia', flag: '🇳🇨' },
    { code: '+64', iso: 'NZ', country: 'New Zealand', flag: '🇳🇿' },
    { code: '+505', iso: 'NI', country: 'Nicaragua', flag: '🇳🇮' },
    { code: '+227', iso: 'NE', country: 'Niger', flag: '🇳🇪' },
    { code: '+234', iso: 'NG', country: 'Nigeria', flag: '🇳🇬' },
    { code: '+683', iso: 'NU', country: 'Niue', flag: '🇳🇺' },
    { code: '+672', iso: 'NF', country: 'Norfolk Island', flag: '🇳🇫' },
    { code: '+389', iso: 'MK', country: 'North Macedonia', flag: '🇲🇰' },
    { code: '+47', iso: 'NO', country: 'Norway', flag: '🇳🇴' },
    { code: '+92', iso: 'PK', country: 'Pakistan', flag: '🇵🇰' },
    { code: '+680', iso: 'PW', country: 'Palau', flag: '🇵🇼' },
    { code: '+507', iso: 'PA', country: 'Panama', flag: '🇵🇦' },
    { code: '+675', iso: 'PG', country: 'Papua New Guinea', flag: '🇵🇬' },
    { code: '+595', iso: 'PY', country: 'Paraguay', flag: '🇵🇾' },
    { code: '+51', iso: 'PE', country: 'Peru', flag: '🇵🇪' },
    { code: '+63', iso: 'PH', country: 'Philippines', flag: '🇵🇭' },
    { code: '+48', iso: 'PL', country: 'Poland', flag: '🇵🇱' },
    { code: '+351', iso: 'PT', country: 'Portugal', flag: '🇵🇹' },
    { code: '+1-787', iso: 'PR', country: 'Puerto Rico', flag: '🇵🇷' },
    { code: '+40', iso: 'RO', country: 'Romania', flag: '🇷🇴' },
    { code: '+7', iso: 'RU', country: 'Russia', flag: '🇷🇺' },
    { code: '+250', iso: 'RW', country: 'Rwanda', flag: '🇷🇼' },
    { code: '+685', iso: 'WS', country: 'Samoa', flag: '🇼🇸' },
    { code: '+378', iso: 'SM', country: 'San Marino', flag: '🇸🇲' },
    { code: '+239', iso: 'ST', country: 'São Tomé and Príncipe', flag: '🇸🇹' },
    { code: '+221', iso: 'SN', country: 'Senegal', flag: '🇸🇳' },
    { code: '+381', iso: 'RS', country: 'Serbia', flag: '🇷🇸' },
    { code: '+248', iso: 'SC', country: 'Seychelles', flag: '🇸🇨' },
    { code: '+232', iso: 'SL', country: 'Sierra Leone', flag: '🇸🇱' },
    { code: '+65', iso: 'SG', country: 'Singapore', flag: '🇸🇬' },
    { code: '+421', iso: 'SK', country: 'Slovakia', flag: '🇸🇰' },
    { code: '+386', iso: 'SI', country: 'Slovenia', flag: '🇸🇮' },
    { code: '+677', iso: 'SB', country: 'Solomon Islands', flag: '🇸🇧' },
    { code: '+252', iso: 'SO', country: 'Somalia', flag: '🇸🇴' },
    { code: '+27', iso: 'ZA', country: 'South Africa', flag: '🇿🇦' },
    { code: '+34', iso: 'ES', country: 'Spain', flag: '🇪🇸' },
    { code: '+94', iso: 'LK', country: 'Sri Lanka', flag: '🇱🇰' },
    { code: '+249', iso: 'SD', country: 'Sudan', flag: '🇸🇩' },
    { code: '+597', iso: 'SR', country: 'Suriname', flag: '🇸🇷' },
    { code: '+46', iso: 'SE', country: 'Sweden', flag: '🇸🇪' },
    { code: '+41', iso: 'CH', country: 'Switzerland', flag: '🇨🇭' },
    { code: '+963', iso: 'SY', country: 'Syria', flag: '🇸🇾' },
    { code: '+886', iso: 'TW', country: 'Taiwan', flag: '🇹🇼' },
    { code: '+992', iso: 'TJ', country: 'Tajikistan', flag: '🇹🇯' },
    { code: '+255', iso: 'TZ', country: 'Tanzania', flag: '🇹🇿' },
    { code: '+66', iso: 'TH', country: 'Thailand', flag: '🇹🇭' },
    { code: '+228', iso: 'TG', country: 'Togo', flag: '🇹🇬' },
    { code: '+676', iso: 'TO', country: 'Tonga', flag: '🇹🇴' },
    { code: '+1-868', iso: 'TT', country: 'Trinidad and Tobago', flag: '🇹🇹' },
    { code: '+216', iso: 'TN', country: 'Tunisia', flag: '🇹🇳' },
    { code: '+90', iso: 'TR', country: 'Turkey', flag: '🇹🇷' },
    { code: '+993', iso: 'TM', country: 'Turkmenistan', flag: '🇹🇲' },
    { code: '+256', iso: 'UG', country: 'Uganda', flag: '🇺🇬' },
    { code: '+380', iso: 'UA', country: 'Ukraine', flag: '🇺🇦' },
    { code: '+971', iso: 'AE', country: 'United Arab Emirates', flag: '🇦🇪' },
    { code: '+44', iso: 'GB', country: 'United Kingdom', flag: '🇬🇧' },
    { code: '+598', iso: 'UY', country: 'Uruguay', flag: '🇺🇾' },
    { code: '+998', iso: 'UZ', country: 'Uzbekistan', flag: '🇺🇿' },
    { code: '+678', iso: 'VU', country: 'Vanuatu', flag: '🇻🇺' },
    { code: '+58', iso: 'VE', country: 'Venezuela', flag: '🇻🇪' },
    { code: '+84', iso: 'VN', country: 'Vietnam', flag: '🇻🇳' },
    { code: '+967', iso: 'YE', country: 'Yemen', flag: '🇾🇪' },
    { code: '+260', iso: 'ZM', country: 'Zambia', flag: '🇿🇲' },
    { code: '+263', iso: 'ZW', country: 'Zimbabwe', flag: '🇿🇼' },
];
